# Uniswap V2 Configuration File

# Description: Configuration file for the Uniswap V2 scanner utility.
# This file specifies parameters such as the range of blocks to scan,
# the Ethereum node URL, the contract address, and the output filename.

blocks_to_scan:
  # Specifies the range of blocks to scan.
  # 'first' denotes the starting block number.
  # 'last' denotes the ending block number.
  first: 19008564
  last: 19550182

# Specifies the URL of the Ethereum node API to use.
# If the 'NODE_URL' environment variable is set, it will override this value.
node_url: http://1.1.1.1:1111

# Specifies the address of the Uniswap V2 contract.
contract_address: "0xd3d2E2692501A5c9Ca623199D38826e513033a17"

# Specifies the name of the output JSON file.
output_filename: uni_eth_state_v0.json


